kind: Deployment
apiVersion: apps/v1
metadata:
  name: llama-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-cli
  template:
    metadata:
      labels:
        app: llama-cli
    spec:
      containers:
        - name: container
          image: 'quay.io/mmartofe/llama-cli:latest'
          env:
            - name: SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: cli-configmap
                  key: SERVER_URL
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  progressDeadlineSeconds: 600